version: '3.7'
services:
  web:
    container_name: instabot
    build:
      context: ./core
      dockerfile: docker/x86-64/Dockerfile
    command: /bin/bash docker/start.sh
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./core:/var/www/html
  db:
    container_name: instabot-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./core/.env.example
  redis:
    image: redis:5.0.5-alpine
