version: '3.7'
services:
  web:
    container_name: arm-instabot
    build:
      context: ./core
      dockerfile: docker/arm/Dockerfile
    command: /bin/bash docker/start.sh
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.example
  db:
    image: hypriot/rpi-mysql
    env_file:
      - .env.example
  redis:
    image: arm32v6/redis:5.0.5-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8583:80"
    depends_on:
      - db
#  front:
#    image: mohsentm/csms-front:latest
#    volumes:
#      - .env.example:/usr/src/app/.env
#    ports:
#      - "3000:3000"
