version: '3.7'
services:
  web:
    container_name: instabot
    build:
      context: ./core
      dockerfile: docker/x86-64/Dockerfile
    command: /bin/bash docker/start.sh
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
      - maildev
    volumes:
      - ./core:/var/www/html
  panel:
    container_name: instabotpanel
    build:
      context: ./panel
      dockerfile: docker/x86-64/Dockerfile
    command: /bin/sh docker/start.sh
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - web
    volumes:
      - ./panel:/usr/src/app
  db:
    container_name: instabot-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./core/.env.example
  redis:
    image: redis:5.0.5-alpine
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25